/* eslint-disable import/prefer-default-export */
/* Populated by react-webpack-redux:action */
const FETCH_START="fetch_start";
const FETCH_END="fetch_end";
const FETCH_SUCCESS_NOVELLIST="fetch_success_novellist";
const REMOVE_ITEM="remove_item";
const FILTERCHANGE="filterChange";
const FETCH_SUCCESS_RECOMMENTLIST="fetch_success_recommentlist";
const INIT_PAGEDATA="INIT_PAGEDATA";
const SAVE_TOKEN="SAVE_TOKEN";
const UPDATEITEMSTATUS="UPDATEITEMSTATUS";
const FILTERINPUTCHANGE="FILTERINPUTCHANGE"
const SHOWDETAIL="SHOWDETAIL";
const HIDEDETAIL="HIDEDETAIL";
const PAGECHANGE="PAGECHANGE";
const TABLESELECTCHANGE="TABLESELECTCHANGE";
const HIDESYSTEMINFO="HIDESYSTEMINFO";
export {
    SHOWDETAIL,
    HIDEDETAIL,
    FETCH_END,
    FETCH_START,
    FETCH_SUCCESS_NOVELLIST,
    REMOVE_ITEM,
    FILTERCHANGE,
    FETCH_SUCCESS_RECOMMENTLIST,
    INIT_PAGEDATA,
    SAVE_TOKEN,
    UPDATEITEMSTATUS,
    FILTERINPUTCHANGE,
    PAGECHANGE,
    TABLESELECTCHANGE,
    HIDESYSTEMINFO
}